### ISSUE TITLE
FTS does not work for identity entities

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/fts#27]
### Environment

- Platform version: 6.9.0 
### FTS does not work for identity entities
* Create identity entity, create an editor for entity
* Enable FTS for entity
Try to create identity entity
Error occurs:
```
java.lang.IllegalStateException: Cannot get primary key value: entity is null
        at com.haulmont.cuba.core.entity.IdProxy.getNN(IdProxy.java:135) ~[cuba-global-6.9.0.jar:6.9.0]
        at com.haulmont.cuba.core.entity.FtsQueue.setObjectEntityId(FtsQueue.java:143) ~[cuba-global-6.9.0.jar:6.9.0]
        at com.haulmont.fts.core.app.FtsSenderBean.persistQueueItem(FtsSenderBean.java:128) ~[fts-core-6.9.0.jar:6.9.0]
        at com.haulmont.fts.core.app.FtsSenderBean.enqueue(FtsSenderBean.java:106) ~[fts-core-6.9.0.jar:6.9.0]
        at com.haulmont.fts.core.app.FtsSenderBean.lambda$enqueue$0(FtsSenderBean.java:85) ~[fts-core-6.9.0.jar:6.9.0]
        at com.haulmont.cuba.core.sys.PersistenceImpl$EntityManagerContextSynchronization.afterCompletion(PersistenceImpl.java:329) ~[cuba-core-6.9.0.jar:6.9.0]
        at org.springframework.transaction.support.TransactionSynchronizationUtils.invokeAfterCompletion(TransactionSynchronizationUtils.java:168) ~[spring-tx-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.invokeAfterCompletion(AbstractPlatformTransactionManager.java:1002) [spring-tx-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.triggerAfterCompletion(AbstractPlatformTransactionManager.java:977) [spring-tx-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:806) [spring-tx-4.3.14.RELEASE.jar:4.3.14.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730) [spring-tx-4.3.14.RELEASE.jar:4.3.14.RELEASE]
```

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[7dde4ce0](https://git.haulmont.com/platform/fts/commit/7dde4ce0cfbe6d5f7b74db8f93e3e015a0666409) in **release_6_9** - FTS does not work for identity entities #27

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[2f0dbc0c](https://git.haulmont.com/platform/fts/commit/2f0dbc0ce77834f695f16734fb5c8f83e026fe36) in **release_6_10** - FTS does not work for identity entities #27

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[aa06de11](https://git.haulmont.com/platform/fts/commit/aa06de1167d8348d9271468113bfccfa2c7abf4a) in **master** - FTS does not work for identity entities #27

**Comment by hraynaud** [comment]
I'm still seeing something similar to this in 6.10 but we're not using FTS
