### ISSUE TITLE
NPE while indexing entity which contains collection with NULL element

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/fts#39]
### Environment

- Platform version: 6.8.9
### Description of the bug or enhancement

- Minimal reproducible example 
[fts_metaproperty.zip](https://github.com/cuba-platform/fts/files/2449513/fts_metaproperty.zip)
Create entity with transient collection metaproperty. Collection must contain NULL values. Try to index entity.
Error occurs: 
```
Caused by: java.lang.NullPointerException: null
    at com.haulmont.fts.core.sys.LuceneIndexer.addLinkedPropertyEx(LuceneIndexer.java:319)
    at com.haulmont.fts.core.sys.LuceneIndexer.createLinksFieldContent(LuceneIndexer.java:291)
    at com.haulmont.fts.core.sys.LuceneIndexer.indexEntity(LuceneIndexer.java:153)
    at com.haulmont.fts.core.app.FtsManager.initIndexer(FtsManager.java:291)
    at com.haulmont.fts.core.app.FtsManager.processQueue(FtsManager.java:231)
    at sun.reflect.GeneratedMethodAccessor1097.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
    at com.sun.proxy.$Proxy176.processQueue(Unknown Source)
    ... 10 common frames omitted
```

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[eb339235](https://git.haulmont.com/platform/fts/commit/eb339235cc1f0dcc4d75ae5b34566dd6e8fbfdd8) in **release_6_8** - NPE while indexing entity which contains collection with NULL element #39

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[942ff653](https://git.haulmont.com/platform/fts/commit/942ff653329c8f7626e542a2253a91f0274bb1f2) in **release_6_9** - NPE while indexing entity which contains collection with NULL element #39

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[749174ac](https://git.haulmont.com/platform/fts/commit/749174ac32b0b29437a62e968867b9746dbd5864) in **release_6_10** - NPE while indexing entity which contains collection with NULL element #39

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[392f81e2](https://git.haulmont.com/platform/fts/commit/392f81e2f9674796b718b26b7773063d64182123) in **master** - NPE while indexing entity which contains collection with NULL element #39
