### ISSUE TITLE
FTS index upgrade fails after any index write operations

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/fts#53]
### Environment
- Platform version: 6.10

### Description of the bug or enhancement
Error can be reproduced here: http://cubadev:9070/app
or on own refapp 6.10 server.

1) If there are no FTS indices yet - execute indexing and stop tomcat
2) Start tomcat.
3) Execute app-core.fts:type=FtsManager -> Upgrade.
```
successful
```
4) Create and save new User with any fields.
5) Wait until it gets indexed:
```
2018-12-28 13:31:22.649 DEBUG [ScheduledRunnerThread-8/app-core/admin] com.haulmont.fts.core.sys.LuceneIndexerBean - Updating document sec$User-899dab3d-c925-7f54-3e08-7cff463b4b19
2018-12-28 13:31:22.815 DEBUG [ScheduledRunnerThread-8/app-core/admin] com.haulmont.fts.core.app.FtsManager - 1 queue items successfully processed
```

6) Try to execute app-core.fts:type=FtsManager -> Upgrade again:
```
2018-12-28 13:31:49.914 ERROR [BackgroundTask-1-admin/app/admin] com.haulmont.fts.core.sys.LuceneIndexMaintenanceBean - Error
org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /home/budarov/projects/platform/6_10/tomcat/work/app-core/ftsindex/write.lock
	at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:139) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
	at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
	at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:948) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
	at org.apache.lucene.index.IndexUpgrader.upgrade(IndexUpgrader.java:167) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
	at com.haulmont.fts.core.sys.LuceneIndexMaintenanceBean.upgrade(LuceneIndexMaintenanceBean.java:64) ~[fts-core-6.10-SNAPSHOT.jar:na]
	at com.haulmont.fts.core.app.FtsManager.upgrade(FtsManager.java:299) [fts-core-6.10-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) [spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) [spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) [spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) [spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at com.sun.proxy.$Proxy181.upgrade(Unknown Source) [na:na]
	at com.haulmont.fts.core.jmx.FtsManager.upgrade(FtsManager.java:78) [fts-core-6.10-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
```

**Comment by andreysubbotin** [comment]
https://github.com/apache/lucene-solr/pull/151/files

**Comment by haulmont-git** [comment]
Git changesets by `subbotin`: 

[5b0a6fa2](https://git.haulmont.com/platform/fts/commit/5b0a6fa25769ead554b8ff06cfa1f2c0fabe024d) in **release_6_10** - FTS index upgrade fails after any index write operations #53
