### ISSUE TITLE
FTS filter doesn't work with new screen API

### ISSUE THREAD

**Issue by andreysubbotin** [cuba-platform/fts#54]
https://www.cuba-platform.com/discuss/t/developmentexception-sessionid-is-not-used-in-the-query-thrown-searching-with-table-full-text-search-feature/8224

### Environment

- Platform version: 7.0

### Description of the bug or enhancement

- Minimal reproducible example
* Create entity in the model
* Add entity to fts config
* Create editor/browser for entity
* Start application, reindex entity
* Try to find entity in the browser by FTS text field 
- Actual behavior
Error:
```
com.haulmont.cuba.core.global.DevelopmentException: Parameter '__sessionId' is not used in the query
	at com.haulmont.cuba.core.app.RdbmsQueryBuilder.getQuery(RdbmsQueryBuilder.java:172)
	at com.haulmont.cuba.core.app.RdbmsStore.createQuery(RdbmsStore.java:634)
	at com.haulmont.cuba.core.app.RdbmsStore.loadList(RdbmsStore.java:222)
	at com.haulmont.cuba.core.app.DataManagerBean.loadList(DataManagerBean.java:74)
	at com.haulmont.cuba.core.app.DataServiceBean.loadList(DataServiceBean.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.haulmont.cuba.core.sys.ServiceInterceptor.aroundInvoke(ServiceInterceptor.java:117)
	at sun.reflect.GeneratedMethodAccessor233.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy238.loadList(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.haulmont.cuba.core.sys.remoting.LocalServiceInvokerImpl.invoke(LocalServiceInvokerImpl.java:94)
	at com.haulmont.cuba.web.sys.remoting.LocalServiceProxy$LocalServiceInvocationHandler.invoke(LocalServiceProxy.java:154)
	at com.sun.proxy.$Proxy34.loadList(Unknown Source)
	at com.haulmont.cuba.client.sys.DataManagerClientImpl.loadList(DataManagerClientImpl.java:57)
	at com.haulmont.cuba.gui.model.impl.CollectionLoaderImpl.load(CollectionLoaderImpl.java:88)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl$LoaderAdapter.refresh(FilterDelegateImpl.java:2938)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.applyFts(FilterDelegateImpl.java:1648)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl$1.actionPerform(FilterDelegateImpl.java:377)
	at com.haulmont.cuba.web.gui.components.WebButton.buttonClicked(WebButton.java:62)
	at com.haulmont.cuba.web.widgets.CubaButton.fireClick(CubaButton.java:76)
	at com.vaadin.ui.Button$1.click(Button.java:57)
```

**Comment by andreysubbotin** [comment]
Changes: 
master: https://github.com/cuba-platform/cuba/commit/f1672eba8e02cebd6e74258cc631457203916d46
release_7_0: https://github.com/cuba-platform/cuba/commit/d6d1ad07aa0b66f314dc3f841ec265dac6aa475f
